export const consoleSections = {
  organizaciones: {
    title: "Organizaciones",
    description:
      "Gestiona clientes contractuales, cadenas y agrupaciones con aislamiento por tenant.",
    action: "Nueva organización",
    columns: ["Organización", "Sedes", "Usuarios activos", "Plan", "Estado"],
    rows: [
      ["Hoteles Miramar", "4", "248", "Professional", "Operativo"],
      ["Restauración Costa Sur", "7", "92", "Business", "Operativo"],
      ["Eventos Mediterráneo", "2", "0", "Starter", "Configurando"],
      ["Oficinas Alcazaba", "3", "41", "Business", "Operativo"],
    ],
  },
  red: {
    title: "Red y gateways",
    description: "Inventario MikroTik, conectividad privada, versiones y estado de configuración.",
    action: "Registrar gateway",
    columns: ["Gateway", "Sede", "Modelo", "RouterOS", "Último heartbeat", "Estado"],
    rows: [
      ["miramar-core-01", "Hotel Miramar Málaga", "RB5009UG+S+", "7.21.5", "Hace 18 s", "Online"],
      ["miramar-pool-01", "Hotel Miramar Málaga", "hAP ax³", "7.21.5", "Hace 22 s", "Online"],
      ["costasur-core-01", "Hotel Costa Sur", "CCR2004", "7.20.6", "Hace 1 min", "Atención"],
      ["eventos-lab-01", "Laboratorio ENTELSAT", "CHR", "7.21.5", "Hace 34 s", "Online"],
    ],
  },
  usuarios: {
    title: "Usuarios WiFi",
    description: "Perfiles minimizados, dispositivos, consentimientos y visitas por sede.",
    action: "Exportación autorizada",
    columns: ["Usuario", "Identificador", "Última sede", "Visitas", "Marketing", "Última conexión"],
    rows: [
      [
        "Usuario #92A7",
        "m•••••@example.com",
        "Hotel Miramar Málaga",
        "6",
        "Consentido",
        "Hace 4 min",
      ],
      [
        "Usuario #31C8",
        "Dispositivo anónimo",
        "Hotel Costa Sur",
        "2",
        "No solicitado",
        "Hace 18 min",
      ],
      [
        "Usuario #6F12",
        "a•••••@example.com",
        "Hotel Miramar Málaga",
        "12",
        "Revocado",
        "Ayer, 22:14",
      ],
      [
        "Usuario #8B44",
        "Voucher VCH-••48",
        "Hotel Miramar Málaga",
        "1",
        "No aplica",
        "Ayer, 19:42",
      ],
    ],
  },
  sesiones: {
    title: "Sesiones",
    description: "Estado RADIUS, consumo y acciones de desconexión con trazabilidad completa.",
    action: "Actualizar",
    columns: ["Sesión", "Usuario", "Gateway", "Duración", "Consumo", "Estado"],
    rows: [
      ["S-7A21F4", "Usuario #92A7", "miramar-core-01", "38 min", "842 MB", "Activa"],
      ["S-C92E10", "Usuario #31C8", "miramar-pool-01", "12 min", "124 MB", "Activa"],
      ["S-1B884C", "Usuario #8B44", "miramar-core-01", "1 h 02 min", "1,8 GB", "Activa"],
      ["S-FEE842", "Usuario #6F12", "costasur-core-01", "44 min", "663 MB", "Finalizada"],
    ],
  },
  dispositivos: {
    title: "Autorizados y bloqueos",
    description: "Controla dispositivos sin navegador y bloqueos temporales por ámbito y motivo.",
    action: "Autorizar dispositivo",
    columns: ["Dispositivo", "MAC minimizada", "Sede", "Política", "Caducidad", "Estado"],
    rows: [
      [
        "TPV Recepción 01",
        "8A:••:••:••:4F:21",
        "Hotel Miramar Málaga",
        "Equipos internos",
        "31 dic 2026",
        "Autorizado",
      ],
      [
        "Smart TV Hab. 204",
        "34:••:••:••:A1:0C",
        "Hotel Miramar Málaga",
        "IoT hotel",
        "Sin caducidad",
        "Autorizado",
      ],
      [
        "Dispositivo #D82C",
        "F2:••:••:••:19:77",
        "Hotel Costa Sur",
        "—",
        "18 ago 2026",
        "Bloqueado",
      ],
    ],
  },
  estadisticas: {
    title: "Estadísticas",
    description:
      "Métricas diferenciadas por usuario, dispositivo, sesión y visita con filtros de alcance.",
    action: "Crear informe",
    columns: ["Informe", "Ámbito", "Periodo", "Generado", "Formato", "Estado"],
    rows: [
      ["Operación semanal", "Todas las sedes", "Últimos 7 días", "Hoy, 06:00", "PDF", "Disponible"],
      ["Consumo por sede", "Hoteles Miramar", "Agosto 2026", "Hoy, 05:45", "XLSX", "Disponible"],
      [
        "Conversión portal",
        "Hotel Costa Sur",
        "Últimos 30 días",
        "Ayer, 23:10",
        "CSV",
        "Disponible",
      ],
    ],
  },
  legal: {
    title: "Legal y privacidad",
    description: "Versiona textos legales, finalidades, consentimientos y solicitudes de derechos.",
    action: "Nuevo documento",
    columns: ["Documento", "Responsable", "Versión", "Idiomas", "Publicado", "Estado"],
    rows: [
      ["Condiciones de uso WiFi", "Hoteles Miramar S.L.", "v3", "ES / EN", "2 ago 2026", "Vigente"],
      ["Política de privacidad", "Hoteles Miramar S.L.", "v5", "ES / EN", "2 ago 2026", "Vigente"],
      [
        "Consentimiento comercial",
        "Hoteles Miramar S.L.",
        "v2",
        "ES / EN",
        "15 jul 2026",
        "Vigente",
      ],
      ["Retención de datos", "ENTELSAT", "Borrador", "ES", "—", "Revisión DPO"],
    ],
  },
  auditoria: {
    title: "Auditoría",
    description:
      "Registro inmutable de acciones sensibles, cambios, accesos y decisiones de autorización.",
    action: "Exportar evidencia",
    columns: ["Fecha", "Actor", "Acción", "Recurso", "Ámbito", "Resultado"],
    rows: [
      [
        "16 ago · 10:42",
        "Francisco M.",
        "portal.publish",
        "Portal Miramar v12",
        "Hotel Miramar",
        "Correcto",
      ],
      [
        "16 ago · 09:18",
        "worker@system",
        "voucher.expire",
        "Lote AGOSTO-26",
        "Hotel Costa Sur",
        "14 registros",
      ],
      [
        "16 ago · 08:01",
        "Técnico ENTELSAT",
        "gateway.config.preview",
        "miramar-core-01",
        "JIT #1842",
        "Correcto",
      ],
      [
        "15 ago · 22:14",
        "admin@costasur",
        "session.disconnect",
        "S-FEE842",
        "Hotel Costa Sur",
        "Correcto",
      ],
    ],
  },
  ajustes: {
    title: "Ajustes",
    description:
      "Configuración del tenant, seguridad, límites contratados e integraciones operativas.",
    action: "Guardar cambios",
    columns: ["Área", "Configuración", "Valor", "Heredado de", "Último cambio", "Estado"],
    rows: [
      ["Seguridad", "Verificación en dos pasos", "Obligatoria", "Tenant", "4 ago 2026", "Activo"],
      ["Localización", "Zona horaria", "Europe/Madrid", "Organización", "12 jul 2026", "Activo"],
      ["Retención", "Accounting identificable", "90 días", "Tenant", "Pendiente DPO", "Revisión"],
      ["Integraciones", "Almacenamiento S3", "Región UE", "Plataforma", "1 jul 2026", "Operativo"],
    ],
  },
} as const;

export type ConsoleSection = keyof typeof consoleSections;
