import { z } from "zod";

export const permissionIds = [
  "tenant.read",
  "tenant.create",
  "tenant.update",
  "tenant.suspend",
  "organization.read",
  "organization.create",
  "organization.update",
  "organization.delete",
  "site_group.read",
  "site_group.create",
  "site_group.update",
  "site_group.delete",
  "site.read",
  "site.create",
  "site.update",
  "site.delete",
  "membership.read",
  "membership.manage",
  "role_assignment.read",
  "role_assignment.manage",
  "zone.read",
  "zone.create",
  "zone.update",
  "zone.delete",
  "ssid.read",
  "ssid.create",
  "ssid.update",
  "ssid.delete",
  "gateway.read",
  "gateway.create",
  "gateway.update",
  "gateway.delete",
  "gateway.monitoring.read",
  "gateway.config.preview",
  "gateway.config.deploy",
  "gateway.config.rollback",
  "gateway.secret.rotate",
  "gateway.secret.reveal",
  "access_policy.read",
  "access_policy.create",
  "access_policy.update",
  "access_policy.delete",
  "login_method.read",
  "login_method.manage",
  "portal.read",
  "portal.create",
  "portal.update",
  "portal.delete",
  "portal.publish",
  "legal.read",
  "legal.create",
  "legal.update",
  "legal.publish",
  "processing_purpose.read",
  "processing_purpose.manage",
  "consent.read",
  "consent.export",
  "user.read",
  "device.read",
  "visit.read",
  "session.read",
  "session.disconnect",
  "pii.read",
  "pii.export",
  "dsr.read",
  "dsr.create",
  "dsr.approve",
  "dsr.execute",
  "voucher.read",
  "voucher.create",
  "voucher.revoke",
  "voucher.extend",
  "voucher.reprint",
  "voucher.export",
  "authorized_entity.read",
  "authorized_entity.manage",
  "blocked_entity.read",
  "blocked_entity.manage",
  "audit.read",
  "audit.export",
  "analytics.read",
  "analytics.export_non_pii",
  "export.download",
] as const;

export const permissionIdSchema = z.enum(permissionIds);
export type PermissionId = z.infer<typeof permissionIdSchema>;

export const roleKeySchema = z.enum([
  "platform_superadmin",
  "entelsat_technician",
  "support_readonly",
  "chain_admin",
  "site_admin",
  "marketing",
  "reception",
  "auditor_dpo",
  "billing",
]);
export type RoleKey = z.infer<typeof roleKeySchema>;

export const authorizationDecisionSchema = z.object({
  allowed: z.boolean(),
  permission: permissionIdSchema,
  reason: z.enum([
    "granted",
    "missing_permission",
    "scope_mismatch",
    "jit_required",
    "reauthentication_required",
    "dual_approval_required",
  ]),
});
export type AuthorizationDecision = z.infer<typeof authorizationDecisionSchema>;
